apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-baseline-conf
data:
  nginx.conf: |
    worker_processes auto;
    events { worker_connections 4096; }
    http {
      access_log /dev/stdout;
      error_log  /dev/stderr warn;

      server {
        listen 0.0.0.0:8080;
        # return a tiny body to minimize file I/O
        location / {
          default_type text/plain;
          return 200 "ok\n";
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-baseline
spec:
  replicas: 1
  selector: { matchLabels: { app: nginx-baseline } }
  template:
    metadata:
      labels: { app: nginx-baseline }
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        command: ["nginx"]
        args: ["-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx
        resources:
          requests: { cpu: "100m", memory: "64Mi" }
          limits:   { cpu: "1",    memory: "256Mi" }
      volumes:
      - name: conf
        configMap:
          name: nginx-baseline-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-baseline-svc
spec:
  selector: { app: nginx-baseline }
  ports:
  - name: http
    port: 80
    targetPort: 8080
