apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-app-tcp-conf
data:
  nginx.conf: |
    worker_processes auto;
    events { worker_connections 4096; }
    http {
      access_log /dev/stdout;
      error_log  /dev/stderr warn;

      # App listens only inside the pod namespace (loopback)
      server {
        listen 127.0.0.1:8081;
        location / {
          default_type text/plain;
          return 200 "ok\n";
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-sidecar-tcp-conf
data:
  nginx.conf: |
    worker_processes auto;
    events { worker_connections 4096; }
    http {
      access_log /dev/stdout;
      error_log  /dev/stderr warn;

      # Public listener: exposed via Service
      server {
        listen 0.0.0.0:8080;

        # Proxy to the app over loopback TCP inside the same pod
        location / {
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://127.0.0.1:8081;
        }
      }

      # Sidecar self health
      server {
        listen 0.0.0.0:9090;
        location = /healthz { return 200 "ok\n"; }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sidecar-tcp
spec:
  replicas: 1
  selector: { matchLabels: { app: nginx-sidecar-tcp } }
  template:
    metadata:
      labels: { app: nginx-sidecar-tcp }
    spec:
      containers:
      - name: app
        image: nginx:1.27-alpine
        command: ["nginx"]
        args: ["-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
        volumeMounts:
        - name: app-conf
          mountPath: /etc/nginx
        resources:
          requests: { cpu: "100m", memory: "64Mi" }
          limits:   { cpu: "2",    memory: "256Mi" }

      - name: sidecar
        image: nginx:1.27-alpine
        command: ["nginx"]
        args: ["-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
        ports:
        - name: http
          containerPort: 8080
        - name: health
          containerPort: 9090
        volumeMounts:
        - name: sidecar-conf
          mountPath: /etc/nginx
        readinessProbe:
          httpGet: { port: 9090, path: /healthz }
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          requests: { cpu: "100m", memory: "64Mi" }
          limits:   { cpu: "1",    memory: "256Mi" }

      volumes:
      - name: app-conf
        configMap: { name: nginx-app-tcp-conf }
      - name: sidecar-conf
        configMap: { name: nginx-sidecar-tcp-conf }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sidecar-tcp-svc
spec:
  selector: { app: nginx-sidecar-tcp }
  ports:
  - name: http
    port: 80
    targetPort: 8080
